spring:
  profiles:
    active: production


google:
  client:
    clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
    clientSecret: xxxxxxxxxxxxxxxxxxxxxxxx
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: basic
    scope:
    - profile
    - email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
discord:
  client:
    clientId: xxxxxxxxxxxxxxxxxx
    clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    accessTokenUri: https://discordapp.com/api/oauth2/token
    userAuthorizationUri: https://discordapp.com/api/oauth2/authorize
    clientAuthenticationScheme: basic
    scope:
    - identify
  resource:
    userInfoUri: https://discordapp.com/api/users/@me